# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa5b29ed274b2c61bf9c1bbb182b294f741c9ebce28237d686725c49a5a0367d210d551d3e7a1818ad1b265788dbe157db58c7b415f27f6b23db185d08f38cbd

test:
  secret_key_base: 445506bd567dc3476904f8f421df48eebd0e5686d7baf5129aeeb114e75b6d3e03777cf47afb1f3e619793618ec501a7847d76e0a44548cb47df45b4a75ea3ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
